const wordMeanings = [
  ["Ability","योग्यता, क्षमता"],
  ["Able","सक्षम"],
  ["Abandon","त्यागना"],
  ["Abandoned","परित्यक्त"],
  ["Abbreviation","संक्षिप्त रूप"],
  ["Abroad","विदेश में"],
  ["Absence","अनुपस्थिति"],
  ["Absolute","पूर्ण"],
  ["Absolutely","बिल्कुल"],
  ["Absorb","अवशोषित करना"],
  ["Abstract","अमूर्त"],
  ["Abundant","प्रचुर"],
  ["Accept","स्वीकार करना"],
  ["Access","पहुंच"],
  ["Accident","दुर्घटना"],
  ["Accompany","साथ जाना"],
  ["Accomplish","पूरा करना"],
  ["Accurate","सटीक"],
  ["Achieve","प्राप्त करना"],
  ["Achievement","उपलब्धि"],
  ["Acquire","प्राप्त करना"],
  ["Act","कार्य करना"],
  ["Action","कार्य"],
  ["Active","सक्रिय"],
  ["Activity","गतिविधि"],
  ["Actual","वास्तविक"],
  ["Actually","वास्तव में"],
  ["Adapt","अनुकूल बनाना"],
  ["Add","जोड़ना"],
  ["Address","पता"],
  ["Admire","प्रशंसा करना"],
  ["Advice","सलाह"],
  ["Advise","सलाह देना"],
  ["Affection","स्नेह"],
  ["Afraid","डरा हुआ"],
  ["Agree","सहमत होना"],
  ["Agreement","सहमति"],
  ["Allow","अनुमति देना"],
  ["Almost","लगभग"],
  ["Alone","अकेला"],
  ["Amazing","अद्भुत"],
  ["Ambition","महत्वाकांक्षा"],
  ["Ancient","प्राचीन"],
  ["Angry","क्रोधित"],
  ["Announce","घोषणा करना"],
  ["Answer","उत्तर"],
  ["Anxious","चिंतित"],
  ["Appear","दिखाई देना"],
  ["Apply","आवेदन करना, लागू करना"],
  ["Appreciate","सराहना करना"],
  ["Approach","दृष्टिकोण, पास आना"],
  ["Arrange","व्यवस्थित करना"],
  ["Arrive","पहुंचना"],
  ["Article","लेख"],
  ["Assist","सहायता करना"],
  ["Attempt","प्रयास करना"],
  ["Attention","ध्यान"],
  ["Attractive","आकर्षक"],
  ["Avoid","बचना"],
  ["Awake","जागा हुआ"],
  ["Aware","जागरूक"],
  ["Beautiful","सुंदर"],
  ["Because","क्योंकि"],
  ["Become","बनना"],
  ["Begin","शुरू करना"],
  ["Behavior","व्यवहार"],
  ["Believe","विश्वास करना"],
  ["Benefit","लाभ"],
  ["Brave","बहादुर"],
  ["Bright","चमकीला"],
  ["Bring","लाना"],
  ["Build","बनाना"],
  ["Busy","व्यस्त"],
  ["Calm","शांत"],
  ["Care","देखभाल"],
  ["Careful","सावधान"],
  ["Cause","कारण"],
  ["Celebrate","मनाना"],
  ["Challenge","चुनौती"],
  ["Change","बदलना"],
  ["Choose","चुनना"],
  ["Clever","चतुर"],
  ["Collect","इकट्ठा करना"],
  ["Comfort","आराम"],
  ["Common","सामान्य"],
  ["Complete","पूरा करना"],
  ["Concern","चिंता"],
  ["Confidence","आत्मविश्वास"],
  ["Confirm","पुष्टि करना"],
  ["Connect","जोड़ना"],
  ["Consider","विचार करना"],
  ["Continue","जारी रखना"],
  ["Courage","साहस"],
  ["Create","बनाना"],
  ["Curious","जिज्ञासु"],
  ["Danger","खतरा"],
  ["Decide","निर्णय लेना"],
  ["Decision","निर्णय"],
  ["Deep","गहरा"],
  ["Defeat","हार"],
  ["Defend","रक्षा करना"],
  ["Demand","मांग"],
  ["Describe","वर्णन करना"],
  ["Desire","इच्छा"],
  ["Develop","विकसित करना"],
  ["Different","अलग"],
  ["Difficult","कठिन"],
  ["Discover","खोज करना"],
  ["Dream","सपना"],
  ["Early","जल्दी"],
  ["Earn","कमाना"],
  ["Easy","आसान"],
  ["Education","शिक्षा"],
  ["Effort","प्रयास"],
  ["Encourage","प्रोत्साहित करना"],
  ["Energy","ऊर्जा"],
  ["Enjoy","आनंद लेना"],
  ["Enough","पर्याप्त"],
  ["Entire","पूरा"],
  ["Environment","पर्यावरण"],
  ["Equal","समान"],
  ["Error","गलती"],
  ["Essential","आवश्यक"],
  ["Excellent","उत्कृष्ट"],
  ["Experience","अनुभव"],
  ["Explain","समझाना"],
  ["Famous","प्रसिद्ध"],
  ["Fear","डर"],
  ["Freedom","स्वतंत्रता"],
  ["Friendly","मित्रवत"],
  ["Future","भविष्य"],
  ["Generous","उदार"],
  ["Goal","लक्ष्य"],
  ["Great","महान"],
  ["Happy","खुश"],
  ["Hard","कठिन"],
  ["Helpful","सहायक"],
  ["Honest","ईमानदार"],
  ["Hope","आशा"],
  ["Important","महत्वपूर्ण"],
  ["Improve","सुधारना"],
  ["Include","शामिल करना"],
  ["Increase","बढ़ाना"],
  ["Independent","स्वतंत्र"],
  ["Information","जानकारी"],
  ["Intelligent","बुद्धिमान"],
  ["Interest","रुचि, ब्याज"],
  ["Knowledge","ज्ञान"],
  ["Kind","दयालु"],
  ["Learn","सीखना"],
  ["Lesson","पाठ"],
  ["Listen","सुनना"],
  ["Lucky","भाग्यशाली"],
  ["Manage","प्रबंध करना"],
  ["Meaning","अर्थ"],
  ["Necessary","आवश्यक"],
  ["Notice","ध्यान देना"],
  ["Opportunity","अवसर"],
  ["Ordinary","साधारण"],
  ["Patient","धैर्यवान"],
  ["Peace","शांति"],
  ["Perfect","पूर्ण"],
  ["Possible","संभव"],
  ["Powerful","शक्तिशाली"],
  ["Practice","अभ्यास"],
  ["Prepare","तैयार करना"],
  ["Problem","समस्या"],
  ["Progress","प्रगति"],
  ["Promise","वादा"],
  ["Protect","रक्षा करना"],
  ["Proud","गर्वित"],
  ["Quick","तेज"],
  ["Quiet","शांत"],
  ["Reason","कारण"],
  ["Receive","प्राप्त करना"],
  ["Respect","सम्मान"],
  ["Result","परिणाम"],
  ["Safe","सुरक्षित"],
  ["Search","खोजना"],
  ["Simple","सरल"],
  ["Skill","कौशल"],
  ["Strong","मजबूत"],
  ["Success","सफलता"],
  ["Support","समर्थन"],
  ["Teach","सिखाना"],
  ["Think","सोचना"],
  ["Together","साथ में"],
  ["Trust","विश्वास"],
  ["Understand","समझना"],
  ["Useful","उपयोगी"],
  ["Value","मूल्य"],
  ["Victory","विजय"],
  ["Weak","कमजोर"],
  ["Wisdom","बुद्धिमत्ता"],
  ["Wonderful","अद्भुत"],
  ["Work","काम"],
  ["Young","युवा"]
];
